from enum import Enum


class TipoDivergencia(Enum):
    ACESSO_DESLIGADO = "ACESSO_DESLIGADO"
    ACESSO_TRANSFERIDO = "ACESSO_TRANSFERIDO"
    PERFIL_INVALIDO = "PERFIL_INVALIDO"
    PERFIL_EXCESSIVO = "PERFIL_EXCESSIVO"
    ACESSO_SEM_VINCULO_RH = "ACESSO_SEM_VINCULO_RH"
